### PR TITLE
Add flatpak manifest

### PR DESCRIPTION
**Pull request by alatiera**

### CODE REVIEW

**Comment by alatiera** [comment]
I don't expect of this being merged anytime soon at least till the runtime is shorted out.

Its mostly that I've had this branch lying around since like 2019 and thought other might want to play with it too.

**Comment by cassidyjames** [comment]
@alatiera d'oh, I didn't see this until I added a manifest based on the Calculator one. At a glance the differences are the cleanup step and pointing to the repo instead of the local directory. Do you see anything I'd need to change?

**Comment by alatiera** [comment]
No worries, I just noticed it was `.json` too.

The cleanup is the standard copy-paste that gets cargo-culted. You can get a terminal inside the app and check if there's any leftovers.

```
$ flatpak run --command=sh com.github.cassidyjames.dippi
```

**Comment by alatiera** [comment]
No worries, I just noticed it was `.json` too.

The cleanup is the standard copy-paste that gets cargo-culted. You can get a terminal inside the app and check if there's any leftovers.

```
$ flatpak run --command=sh com.github.cassidyjames.dippi
```

**Comment by alatiera** [comment]
One thing I am not sure is this line `  - '--metadata=X-DConf=migrate-path=/com/github/cassidyjames/dippi/'`. I think it only applies to other flatpak and won't migrate your `.local/share` things

**Comment by alatiera** [comment]
(oh looks like I had forgot to close this PR)

**Pull request closed without merging**
